// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJb2IJUqaVcWg-hkx_CFspE-kZmXKTtA',
    appId: '1:739017304034:web:2c15d626c0acf3bab2fbbb',
    messagingSenderId: '739017304034',
    projectId: 'project-fcii',
    authDomain: 'project-fcii.firebaseapp.com',
    storageBucket: 'project-fcii.appspot.com',
    measurementId: 'G-KD2G26EXT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvZEpaXW04z8dNVwdUPpUx-7sS5Rn9ksY',
    appId: '1:739017304034:android:44d2a411847e3bf5b2fbbb',
    messagingSenderId: '739017304034',
    projectId: 'project-fcii',
    storageBucket: 'project-fcii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkCefz0s35KOFwWjclGKJ2dqmv-5xJPCo',
    appId: '1:739017304034:ios:81296816a8c99bbfb2fbbb',
    messagingSenderId: '739017304034',
    projectId: 'project-fcii',
    storageBucket: 'project-fcii.appspot.com',
    iosBundleId: 'com.example.projectFcii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkCefz0s35KOFwWjclGKJ2dqmv-5xJPCo',
    appId: '1:739017304034:ios:81296816a8c99bbfb2fbbb',
    messagingSenderId: '739017304034',
    projectId: 'project-fcii',
    storageBucket: 'project-fcii.appspot.com',
    iosBundleId: 'com.example.projectFcii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqJb2IJUqaVcWg-hkx_CFspE-kZmXKTtA',
    appId: '1:739017304034:web:cb9106ff0de28836b2fbbb',
    messagingSenderId: '739017304034',
    projectId: 'project-fcii',
    authDomain: 'project-fcii.firebaseapp.com',
    storageBucket: 'project-fcii.appspot.com',
    measurementId: 'G-BZDKMML89L',
  );
}
